#!/bin/bash

export do_token="PUT YOUR PERSONAL ACCESS TOKEN HERE"
export do_spaces_id="PUT YOUR SPACES ACCESS KEY HERE"
export do_spaces_key="PUT YOUR SPACES ACCESS SECRET HERE"

#This script should be hosted some were in DO
curl https://statuspage-demo.nyc3.digitaloceanspaces.com/statuspage-launch.sh | sudo bash
