---

- hosts: web
  gather_facts: false
  become: yes

  pre_tasks:
  - name: Wait 600 seconds for target connection to become reachable/usable
    wait_for_connection:

  tasks:

  - name: Create systemd service configuration
    template:
      src: templates/statuspage-demo.service.j2
      dest: /lib/systemd/system/statuspage-demo.service

  - name: Start statuspage-demo systemd service
    systemd:
      name: statuspage-demo
      state: started
      enabled: True
      daemon_reload: yes
